name: SonarCloud with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan with Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Test Docker Connection
      run: |
        docker run hello-world

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        docker run --rm \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli:latest \
          sonar-scanner \
          -Dsonar.organization=abhishekherbertsamuel \
          -Dsonar.projectKey=mern-stack-backend \
          -Dsonar.sources=/usr/src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

